services:
  infrared:
    image: haveachin/infrared:latest
    container_name: infrared
    restart: always
    ports:
      - 25565:25565/tcp
    #networks:
    #  - minecraft_net
    volumes:
      - ./data/infrared:/etc/infrared
  mc-latest:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - 25566:25565
    environment:
      EULA: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data/mc-latest:/data
  mc-modded:
    image: itzg/minecraft-server:java8
    container_name: mc-modded
    ports:
      - 25567:25565
    environment:
      EULA: "TRUE"
      TYPE: AUTO_CURSEFORGE
      VERSION: 1.12.2
      MEMORY: 4G
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/sevtech-ages
      CF_API_KEY: ${CF_API_KEY}
      CURSEFORGE_FILES: hwyla # Nessesary to fufill a dependency problem for the sevtech modpack
      JVM_OPTS: -Dfml.queryResult=confirm # Nessesary to auto accept that the world might be broken, wouldn't start up without it
    volumes:
      - ./data/mc-modded:/data
  mc-1.21.4-fabric:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25568:25565
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.21.4
      MODS: >
        https://cdn.modrinth.com/data/P7dR8mSH/versions/ZNwYCTsk/fabric-api-0.118.0%2B1.21.4.jar

        https://cdn.modrinth.com/data/MnavVAzj/versions/14BzXUCO/VeinminerMod-1.21.4-1.0.jar

        https://mediafilez.forgecdn.net/files/5886/317/saplanting-1.21.3-fabric-1.3.1.jar
    volumes:
      - ./data/mc-1.21.4-fabric:/data
networks: {}
