# This is deployed on dockge on the truenas machine

services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - /mnt/pool/StorageNAS/Media/Audio/Music/Beets/config:/config
      - /mnt/pool/StorageNAS/Media/Audio/Music:/music
      - /mnt/pool/StorageNAS/Media/Audio/Music/IngestFolder:/downloads
    ports:
      - 8337:8337
    restart: unless-stopped
networks: {}
