services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 3000:3000 # should be owner of volumes
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - /mnt/pool/StorageNAS/docker/navidrome/data:/data
      - /mnt/pool/StorageNAS/Media/Audio/Music/Library:/music:ro
networks: {}
