services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 3005:3000
      - 3001:3001
    shm_size: 1gb
    restart: unless-stopped
networks: {}
