services:
  scriberr-old:
    #image: ghcr.io/rishikanthc/scriberr:latest
    image: ghcr.io/rishikanthc/scriberr:nightly
    # build:
    #  context: .
    #  dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_started
      pocketbase:
        condition: service_started
    ports:
      - 3030:3000 # Scriberr UI
      - 9243:9243 # Optionally expose JobQueue UI
      - 8082:8080 # Optionally expose Database Management UI
    environment:
      # - OPENAI_API_KEY=>
      - OPENAI_ENDPOINT=http://192.168.10.35:11434/v1
      - OPENAI_MODEL=llama3.2:latest # Ensure this model matches in `ollama-models` service
      - OPENAI_ROLE=user
      - POCKETBASE_ADMIN_EMAIL=tyler@thechartrands.com
      - POCKETBASE_ADMIN_PASSWORD=VKgcxopda7ol
      - POCKETBASE_URL=http://192.168.10.31:8085
      - DATABASE_URL=http://192.168.10.31:8085
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SCRIBO_FILES=/scriberr
      - DEV_MODE=false
      - NVIDIA=false # set to true if you have one
      - CONCURRENCY=1 # Adjut cautiously according to hardware limits
    volumes:
      - ./scriberr/pb_data:/app/db
      - ./scriberr:/scriberr
      - ./scriberr/models:/models
  redis:
    image: redis:7-alpine
    volumes:
      - ./.dockerdata/redis:/data
  pocketbase:
    image: ghcr.io/rishikanthc/pocketbase:22.22
    environment:
      - POCKETBASE_ADMIN_EMAIL=tyler@thechartrands.com # Replace with your admin email
      - POCKETBASE_ADMIN_PASSWORD=VKgcxopda7ol # Replace with your admin password
    ports:
      - 8085:8080 # Expose PocketBase on port 8080
    volumes:
      - ./pb_data:/pb/pb_data # Mount the PocketBase data directory for persistence
    restart: unless-stopped # Always restart unless explicitly stopped
networks: {}
